#!/usr/bin/env bash

green='\033[0;32m'
red='\033[0;31m'
yellow='\033[0;33m'
blue='\033[0;34m'
strike='\033[9m'
nc='\033[0m'

build_args=$@

# get the path of this file
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd $DIR

success()
{
    msg=$1
    echo -e "👉 ${green}${msg}${nc}"
}

failure()
{
    msg=$1
    echo -e "🤏 ${red}${strike}${msg}${nc}"
}

build_target()
{
    target=$1

    cd src/$target
    make $build_args > /dev/null

    if [ $? -eq 0 ]; then
        success $target
    else
        failure $target
    fi

    cd $DIR
}

build_target lic
build_target vm
build_target interpreter
